### ISSUE TITLE
Addon no longer works with Visual studio 2015, openframworks 0.9.4

### ISSUE THREAD

**Issue by nathanblanchard12** [bakercp/ofxSQLiteCpp#7]
I am getting many compiling errors. :)

**Comment by bakercp** [comment]
More information please.  Did it work with 0.9.3? What are the steps to reproduce the issue, what specific errors are you getting, etc.

**Comment by nathanblanchard12** [comment]
![screenshot 2](https://cloud.githubusercontent.com/assets/3227980/19506595/cb886a60-959a-11e6-88d9-91a996f97b90.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/3227980/19506594/cb82afda-959a-11e6-85a4-65b5e2172a14.png)

These compilation error happens during the build process, I've been trying this for a while and I usually get the same build errors.

**Comment by bakercp** [comment]
This looks like it could be a VS project file setting problem.  A quick
Google got me these

https://www.google.com/search?q=sqlite3+cannot+convert+void+to+char&oq=sqlite3+cannot+convert+void+to+char

Maybe regenerate your project with the project generator as a start?

**Comment by nathanblanchard12** [comment]
This solution worked for me. Thank you very much. 
This link helped me:
http://stackoverflow.com/questions/27089460/compiling-sqlite-with-visual-studio-c-2013-throws-error-for-c-file

**Comment by bakercp** [comment]
Nice. So the project generator didn't set this automatically?

**Comment by mhashmi** [comment]
Hi @bakercp,

The issue also exists on other platforms (at least android when compiling on a mac).

I am getting the following during compile: 

    error: invalid argument '-std=c++14' not allowed with 'C/ObjC'

Note: this is not just happening for sqlitecpp, but other addons as well (some of them my own) that are compiling c files. Also, this was working correctly with 0.9.3 I believe. 

If I manage to fix the issue I'll update this post, but maybe a mention on the primary OF forum is warranted here.

Also, thank you for all the excellent add-ons 👍

**Comment by gijsoman** [comment]
Hi There!

Here is a visualization on how to fix this problem. Just a visualization. I don't take credits for the actual solution ofcourse.

Solution source: http://stackoverflow.com/questions/27089460/compiling-sqlite-with-visual-studio-c-2013-throws-error-for-c-file

1. Create Project
![projectcreation](https://cloud.githubusercontent.com/assets/17549581/22891446/afe2ae70-f20f-11e6-8dcd-0da8067cd680.png)

2. Go to the properties of the file located in this path in the solution explorer: **"ProjectName"/addons/ofxSQLiteCpp/libs/SQLiteCPP/sqlite3/sqlite3.c**
![properties](https://cloud.githubusercontent.com/assets/17549581/22891556/117cd372-f210-11e6-9c01-888a5978444d.png)

3. In the properties menu go to **C/C++ -> Advanced -> Compile As** and Set this to **Compile as C Code (/TC)**
![settoc](https://cloud.githubusercontent.com/assets/17549581/22891728/8a607adc-f210-11e6-8d44-80af3f2976f7.png)

4. Now go to **C/C++ -> General -> No Common Language RunTime Support** and set it to **No Common Language RunTime Support**
![languageruntime](https://cloud.githubusercontent.com/assets/17549581/22891796/be2234be-f210-11e6-9c7e-2da0d973ff07.png)

5. Now build it and enjoy it without errors :D.
![succes](https://cloud.githubusercontent.com/assets/17549581/22891866/ffef44f4-f210-11e6-891f-07cd16f56a07.png)

**Comment by edovino** [comment]
btw - this happens with oF 0.9.8 on Windows, too. Linux GCC 6.3.1 just gives a warning about using the `--std=c++11` for C code, but merrily continues.

**Comment by johanjohan** [comment]
does not compile win10 of098:
1>v:\00shared\dev8\of\of_v0.9.8_vs_release\addons\ofxsqlitecpp\src\SQLiteCppUtils.h(30): fatal error C1083: Cannot open include file: 'json/json.h': 
No such file or directory (compiling source file ..\..\..\addons\ofxSQLiteCpp\src\SQLiteCppUtils.cpp)

only jsons in 098 are:
of_v0.9.8_vs_release\libs\poco\include\Poco\JSON\JSON.h
of_v0.9.8_vs_release\addons\ofxIO\libs\json\include\json.hpp

any hint? thx, jjj

EDIT: ok! I added ofxJSON and now it works.
